version: "3.9"
services:
  #build server
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    links:
      - "gogs"
  #version control
  gogs:
    image: gogs/gogs:latest
    ports:
      - "3000:3000"
      - "50022:22"
    volumes:
      - gogs_data:/data
  #maven slave
  maven:
    build:
      context: .
      dockerfile: "maven-dockerfile"
      args:
        mavensecret:
    links:
      - "jenkins"
    depends_on:
      - "jenkins"
  #node slave
  nodejs:
    build:
      context: .
      dockerfile: "nodejs-dockerfile"
      args:
        nodejssecret:
    links:
      - "jenkins"
    depends_on:
      - "jenkins"
volumes:
  jenkins_home:
  gogs_data:
